docker_wae/home/routes.py
from flask import Blueprint,render_template,url_for, flash, redirect, request, abort, session,jsonify
from docker_wae import app,db,bcrypt,login_manager
from flask_login import login_user, current_user, logout_user, login_required
from docker_wae.models import User
import docker


blue = Blueprint('home',__name__,template_folder='templates')
client = docker.APIClient(base_url='unix://var/run/docker.sock')

#Dashboard
@blue.route('/home')
@login_required
def home():
	running = 0
	stop = 0
	
	for i in range(len(client.containers(all=True))):

		if client.containers(all=True)[i]['State'] == 'created' or client.containers(all=True)[i]['State'] == 'exited':
			stop = stop + 1

		elif client.containers(all=True)[i]['State'] == 'running':
			running = running + 1

	return render_template('home/home.html',title="Docker WAE : Home",client=client,running=running,stop=stop)

#Image Template
@blue.route('/images')
@login_required
def images():
	return render_template('home/images.html',title="Docker WAE : Images",client=client)

#Inspect image template
@blue.route('/inspect/image_template/<image_id>')
@login_required
def inspect_image_template(image_id):

	inspect_image = client.inspect_image(image_id)
	return render_template('home/inspect_image_template.html',title='Docker WAE : Inspect Image Template',inspect_image=inspect_image)

#Download image from Docker Hub
@blue.route('/image_template/download')
@login_required
def download_image_template():

	return render_template('home/download_image_template.html',title='Docker WAE : Download Image Template')

#Search Image in Docker Hub
@blue.route('/image_template/search',methods=['GET','POST'])
@login_required
def search_img_hub():
	if request.method == 'POST':

		if request.form['searchimagetag'] != '':
			searchimage = client.search(request.form['searchimagename']+':'+request.form['searchimagetag'])
			len_searchimage = len(client.search(request.form['searchimagename']+':'+request.form['searchimagetag']))
		else:
			searchimage = client.search(request.form['searchimagename']+':latest')
			len_searchimage = len(client.search(request.form['searchimagename']+':latest'))

	return render_template('home/download_image_template.html',title='Docker WAE : Download Image Template',searchimage=searchimage,len_searchimage=len_searchimage,result=request.form['searchimagename']+':'+request.form['searchimagetag'])



#User Logout
@blue.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user_management.login'))

docker_wae/home/templates/home/download_image_template.html
{% extends 'home/layout.html' %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
				<nav aria-label="breadcrumb">
  					<ol class="breadcrumb">
    					<li class="breadcrumb-item"><a href="{{url_for('home.images')}}">Images Templates</a></li>
    					<li class="breadcrumb-item active" aria-current="page">Download</li>
  					</ol>
				</nav>
				<div class="row">
					<div class="col"></div>
					<div class="col-md-7	">
						<form method="POST" action="{{url_for('home.search_img_hub')}}">
							<div class="input-group mb-3">
								<input type="text" name='searchimagename' class="form-control" id='searchimagename'placeholder="Image Template name" required="">
								
								<input type="text" name='searchimagetag' class="form-control" placeholder="Image Template Tage name">
								<div class="input-group-append">
    								<button class="btn btn-outline-secondary" type="submit">Search</button>
  								</div>
							</div>
						</form>
					</div>
					<div class="col-md-3"></div>
				</div>
				<p>{{result}}</p>
				<table id="imagetable" class="table table-hover table-sm table-striped display pt-2">
					<thead class="thead-dark">
						<tr>
							<th scope="col">Name</th>
							<th scope="col">Official</th>
							<th scope="col">Automated</th>
							<th scope="col">Ratings</th>
							<th scope="col">Description</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for i in searchimage %}
						<tr>
							<td>{{i['name']}}</td>
							<td>{{i['is_official']}}</td>
							<td>{{i['is_automated']}}</td>
							<td>{{i['star_count']}}</td>
							<td>{{i['description']}}</td>
							<td><a href="#" class="badge badge-success downloadimgbtn" id=downloadimgbtn onclick="pullimage(this)">Download</a></td>
							<script type="text/javascript">

								function pullimage(obj){
									var imgname = $(obj).closest('tr').find('td:first-child').text();
									console.log(imgname);
									/*$(obj).text("Pulling");*/
								};
							</script>
						</tr>	
						{% endfor %}
					</tbody>
				</table>
			</main>
		</div>
	</div>
{% endblock content %}

docker_wae/home/templates/home/home.html
{% extends 'home/layout.html' %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    			<h1 class="h4">Dashboard</h1>
    		</div>
    		<p class="h6">Docker Client Information</p>
    		<span class="badge badge-dark rounded-0 ">{{client.version()['Platform']['Name']}} Edition</span>
    		<span class="badge badge-warning rounded-0 mr-3">{{client.version()['Components'][0]['Version']}}</span>
    		<span class="badge badge-dark rounded-0">Api Version</span>
    		<span class="badge badge-warning rounded-0">{{client.version()['Components'][0]['Details']['ApiVersion']}}</span>
    		<div class="row border-bottom">
    			<div class="col-xl-3 col-md-6 pt-4">
    				<div class="alert alert-dark text-center" role="alert">
    					<i class="fas fa-clone"></i> Image Templates
    					<hr>
    					<p>Locally Available</p><h5 class="text-center"><span class="badge badge-primary">{{client.images() | length }}</span></h5>
                        <hr>
                        <a class="small text-dark stretched-link" href="{{url_for('home.images')}}">View Details</a>
					</div>
                </div>
                <div class="col-xl-3 col-md-6 pt-4">
                	<div class="alert alert-dark text-center" role="alert">
                		<i class="fas fa-box"></i> Containers 
                		<hr>
                        <div class="row">
                            <div class="col">
                                <p>Running</p> <i class="fas fa-thumbs-up mr-2"></i>
                                <span class="badge badge-primary">{{running}}</span>
                            </div>
                            <div class="col">
                                <p>Stopped</p><i class="fas fa-thumbs-down mr-2"></i>
                                <span class="badge badge-primary">{{stop}}</span>
                            </div>
                        </div>
                        <hr>
                        <a class="small text-dark stretched-link" href="#">View Details</a>
                	</div>
                </div>
                <div class="col-xl-3 col-md-6 pt-4">
                    <div class="alert alert-dark text-center" role="alert">
                        <i class="fas fa-hdd"></i> Volumes
                        <hr>
                        <p>Attached Volumes</p><h5 class="text-center"><span class="badge badge-primary">{{client.volumes() | length - 1 }}</span></h5>
                        <hr>
                        <a class="small text-dark stretched-link" href="#">View Details</a>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 pt-4">
                   <div class="alert alert-dark text-center" role="alert">
                        <i class="fas fa-network-wired"></i> Networks
                        <hr>
                        <p>Available Networks</p><h5 class="text-center"><span class="badge badge-primary">{{client.networks() | length }}</span></h5>
                        <hr>
                        <a class="small text-dark stretched-link" href="#">View Details</a>
                   </div>
                </div>
    		</div>	
    	</main>
   	</div> 
</div>
{% endblock content %}

docker_wae/home/templates/home/images.html
{% extends 'home/layout.html' %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
			<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
				<h1 class="h4">Images Templates</h1>
				<a class="btn btn-success btn-sm" href="{{url_for('home.download_image_template')}}" data-toggle="tooltip" data-placement="bottom" title="Download Image Templates from Docker Hub">
					<i class="fas fa-arrow-circle-down"></i>
				</a>
			</div>

			<table id="imagetable" class="table table-hover table-sm table-striped display pt-2">
				<thead class="thead-dark">
					<tr>
						<th scope="col">REPOSITORY</th>
						<th scope="col">TAG</th>
						<th scope="col">IMAGE ID</th>
						<th scope="col">CREATED</th>
						<th scope="col">SIZE</th>
						<th scope="col">Detail</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					{% for i in client.images() %}
						<tr>
							<td>{{i['RepoTags'][0].split(':')[0]}}</td>
							<td>{{i['RepoTags'][0].split(':')[1]}}</td>
							<td>{{i['Id'].split(':')[1][:12]}}</td>
							<td>{{i['Created']}}</td>
							<td>{{i['Size']}}</td>
							<td><a href="{{url_for('home.inspect_image_template',image_id=i['Id'].split(':')[1][:12])}}">Inspect</a></td>
							<td><a href="#" class="badge badge-danger">Delete</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</main>
	</div>
</div>
{% endblock content %}

docker_wae/home/templates/home/inspect_image_template.html
{% extends 'home/layout.html' %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
			<nav aria-label="breadcrumb">
  				<ol class="breadcrumb">
    				<li class="breadcrumb-item"><a href="{{url_for('home.images')}}">Images Templates</a></li>
    				<li class="breadcrumb-item active" aria-current="page">Inspect</li>
  				</ol>
			</nav>
			<div class="card border-0 rounded-0">
				<div class="card-header">
					<span class="badge badge-dark ml-2 border-0 rounded-0 text-left">Image Template</span><span class="badge badge-warning rounded-0">{{inspect_image['RepoTags'][0]}}</span>
				</div>
				<div class="card-body bg-dark text-white">
					{{inspect_image}}
				</div>
			</div>
			
		</main>
	</div>
</div>
{% endblock content %}

docker_wae/home/templates/home/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/dashboard.css')}}">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
     <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
     <style type="text/css">
       .pagination-page-info{
        padding:.6em;padding-left:0;width:40em;margin:.5em;margin-left:0;font-size:11px;
        }
       .pagination-page-infob {
        color: black;background:#6aa6ed;padding-left:2px;padding:.1em.25em;font-size:100%;
        }
     </style>
    <title>{{title}}</title>
  </head>
  <body>
  	<!--Top NavBar-->
  	<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  	 	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Docker Web Access Engine</a>
      	<ul class="navbar-nav px-3">
      		{% if current_user.is_authenticated %}
        		<li class="nav-item text-nowrap">
          			<a class="nav-link" href="{{url_for('home.logout')}}">Sign out</a>
        		</li>

        	{% endif %}	
      	</ul>
    </nav>
    <!--Sidebar-->
    <div class="container-fluid">
    	<div class="row">
        	<nav class="col-md-2 d-none d-md-block sidebar  border-right">
          		<div class="sidebar-sticky">
            		<ul class="nav flex-column">
              			<li class="nav-item">
                			<a class="nav-link" href="{{url_for('home.home')}}">
                  				<i class="fas fa-tachometer-alt"></i> Dashboard
                			</a>
              			</li>
              			<li class="nav-item">
                			<a class="nav-link" href="{{url_for('home.images')}}">
                  				<i class="fas fa-clone"></i> Images Templates 
                			</a>
              			</li>
              			<li class="nav-item">
                			<a class="nav-link" href="#">
                  				
                  				<i class="fas fa-box"></i> Containers
                			</a>
              			</li>
              			<li class="nav-item">
                			<a class="nav-link" href="#">
                  				
                  				<i class="fas fa-hdd"></i> Volumes
                			</a>
              			</li>
              			<li class="nav-item">
                			<a class="nav-link" href="#">
                  				
                  				<i class="fas fa-network-wired"></i> Networking
                			</a>
              			</li>
              		</ul>
          		</div>
    		</nav>
    	</div>
    </div>
    <!--Main-->
    {% block content %}
    {% endblock content %}
    <!--Footer-->
    <div class="footer container-xl width-full p-responsive" role="contentinfo">
    	<div class="container pt-3">
       		<p class="text-center text-decoration-none ">&copy; Docker Web Access Engine <small class="text-info">Powered by Flask</small></p>
   		</div>
    </div>
  	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="{{url_for('static',filename='js/custom.js')}}"></script>
  </body>
</html>