docker_wae/user_management/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from docker_wae.models import User

#Login Form
class LoginForm(FlaskForm):
	email = StringField('Email',validators=[DataRequired(),Email()])
	password = PasswordField('Password',validators=[DataRequired()])
	submit = SubmitField('Login')


#Registration Form
class RegistrationForm(FlaskForm):
	username = StringField('Username',validators=[DataRequired(),Length(min=2,max=20)])
	email = StringField('Email',validators=[DataRequired(),Email()])
	password = PasswordField('Password',validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password',validators=[DataRequired(),EqualTo('password')])
	submit = SubmitField('Register Account')

	def validate_username(self,username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('That username is taken. Please choose a diffrent one.')

	def validate_email(self,email):
		user = User.query.filter_by(email=email.data).first()

		if user:
		   raise ValidationError('That email is taken. Please choose a diffrent one.')

docker_wae/user_management/routes.py
from flask import Blueprint,render_template,url_for, flash, redirect, request, abort, session,jsonify
from docker_wae import app,db,bcrypt,login_manager
from docker_wae.user_management.forms import LoginForm,RegistrationForm
from flask_login import login_user, current_user, logout_user, login_required
from docker_wae.models import User

blue = Blueprint('user_management',__name__,template_folder='templates')

@blue.route('/',methods=['GET','POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password,form.password.data):
			login_user(user)
			next_page = request.args.get('next')
			print("HELLO")
			return redirect(next_page) if next_page else redirect(url_for('home.home'))
		else:
			flash('Login Unsuccessful. Please check email or password','danger')

	return render_template('user_management/login.html',form=form)

@blue.route('/register',methods=['GET','POST'])
def register():
	
	if current_user.is_authenticated:
		return redirect(url_for('user_management.login'))

	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password,password_decrypted=form.password.data)
		db.session.add(user)
		db.session.commit()
		
		flash(f'Your Account has been created! You are now able to login','success')
		return redirect(url_for('user_management.login'))

	return render_template('user_management/register.html',form=form)

docker_wae/user_management/templates/user_management/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style type="text/css">
    	.bg-gradient-primary{
    		background-color:#2C3E50 ;
    	}
    }
    </style>
    <title>Docker WAE</title>
  </head>
  <body  class="bg-gradient-primary">
  	 <!--Messages-->
    <div class="container pt-3">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category,message in messages %}
                <div class="alert alert-{{ category }}">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                  {{message}}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  	<div class="container">
  		{% block content %}
  		{% endblock content %}
  	</div>
  	<!--Footer-->
    <div class="footer container-lg width-full px-3" role="contentinfo">
      <hr>
       <p class="text-center text-white text-decoration-none">&copy; Docker Web Access Engine <small class="text-info">Powered by Flask</small> </p>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

docker_wae/user_management/templates/user_management/login.html
{% extends 'user_management/layout.html' %}
{% block content %}
	 <div class="row justify-content-center">
      	<div class="col-xl-10 col-lg-12 col-md-9">
        	<div class="card o-hidden border-0 shadow-lg my-5">
          		<div class="card-body p-0">
            		<div class="row">
              			<div class="col-lg-3"></div>
              			<div class="col-lg-6">
                			<div class="p-5">
                  				<div class="text-center">
                  					<h1 class="h4 text-gray-900 mb-4">Docker Web Access Engine</h1>
                    				<h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  				</div>
                  			<form class="user" method="POST" action="">
                  				{{form.hidden_tag()}}
                    			<div class="form-group">
                    				{% if form.email.errors %}
                      					{{ form.email(class="form-control form-control-user is-invalid",placeholder="Email Address")}}
                      					<div class="invalid-feedback">
                      						{% for error in form.email.errors %}
                      							<span>{{ error }}</span>
                      						{% endfor %}
                      					</div>
                    				{% else %}
                    					{{ form.email(class="form-control form-control-user ",placeholder="Email Address")}}
                    				{% endif %}
                    			</div>
                    			<div class="form-group">
                    				{% if form.password.errors %}
                      					{{ form.password(class="form-control form-control-user is-invalid",placeholder="Password")}}
                    				{% else %}
                    					{{ form.password(class="form-control form-control-user",placeholder="Password")}}
                    				{% endif %}
                    			</div>
                    				{{ form.submit(class="btn btn-primary btn-user btn-block")}}
                  			</form>
                  			<hr>
                  			<div class="text-center">
                    			<a class="small" href="{{ url_for('user_management.register') }}">Create an Account!</a>
                  			</div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

{% endblock content %}

docker_wae/user_management/templates/user_management/register.html
{% extends 'user_management/layout.html' %}
{% block content %}
	<div class="row justify-content-center">
      	<div class="col-xl-10 col-lg-12 col-md-9">
        	<div class="card o-hidden border-0 shadow-lg my-5">
          		<div class="card-body p-0">
            		<div class="row">
              			<div class="col-lg-3"></div>
              			<div class="col-lg-6">
                			<div class="p-5">
                  				<div class="text-center">
                  					<h1 class="h4 text-gray-900 mb-4">Docker Web Access Engine</h1>
                    				<h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                  				</div>
                  			<form class="user" method="POST" action="">
                  				{{ form.hidden_tag() }}

                    			<div class="form-group">
                    				{% if form.email.errors %}
                    					{{ form.email(class="form-control form-control-user is-invalid",placeholder="Email Address") }}
                    					<div class="invalid-feedback">
                    						{% for error in form.email.errors %}
                    							<span>{{ error }}</span>
                    						{% endfor %}
                    					</div>
                    				{% else %}
                    					{{ form.email(class="form-control form-control-user",placeholder="Email Address") }}
                    				{% endif %}
                    			</div>
                    			<div class="form-group">
                    				{% if form.username.errors %}
                      					{{ form.username(class="form-control form-control-user is-invalid ",placeholder="Username")}}
                      					<div class="invalid-feedback">
                      						{% for error in form.username.errors %}
                      							<span>{{ error }}</span>
                      						{% endfor %}
                      					</div>
                      				{% else %}
                      					{{ form.username(class="form-control form-control-user",placeholder="Username")}}
                    				{% endif%}
                    			</div>
                    			<div class="form-group">
                    				{% if form.password.errors %}
                      					{{ form.password(class="form-control form-control-user is-invalid",placeholder="Password")}}
                      					<div class="invalid-feedback">
                      						{% for error in form.password.errors %}
                      							<span>{{ error }}</span>
                      						{% endfor %}
                      					</div>
                    				{% else %}
                    					{{ form.password(class="form-control form-control-user",placeholder="Password")}}
                    				{% endif %}
                    			</div>
                    			<div class="form-group">
                      				{% if form.confirm_password.errors %}
                      					{{ form.confirm_password(class="form-control form-control-user is-invalid",placeholder="Confirm Password")}}
                      					<div class="invalid-feedback">
                      						{% for error in form.confirm_password.errors %}
                      							<span>{{ error }}</span>
                      						{% endfor %}
                      					</div>
                    				{% else %}
                    					{{ form.confirm_password(class="form-control form-control-user",placeholder="Confirm Password")}}
                    				{% endif %}
                    			</div>
                    				{{ form.submit(class="btn btn-primary btn-user btn-block")}}
                  			</form>
                  			<hr>
                  			<div class="text-center">
                    			<a class="small" href="{{url_for('user_management.login')}}">Already have an account? Login!</a>
                  			</div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

{% endblock content %}